name: Pull requests
on:
  pull_request:
    types:
      [
        labeled,
        edited,
        opened,
        closed,
        reopened,
        synchronize,
        ready_for_review,
        review_requested,
        auto_merge_enabled,
      ]

jobs:
  title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  local-title:
    name: Validate PR title local
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/semantic-pull-request/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          scope: '@temp-test-org2'
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORG_PAT_TEST_TEMP_ORG2_PACKAGE_READ }}

      - name: Testing
        run: npm run test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          scope: '@temp-test-org2'
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORG_PAT_TEST_TEMP_ORG2_PACKAGE_READ }}

      - name: Build
        run: npm run build
