name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    name: Release local
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release please
        uses: ./.github/actions/release-please/
        with:
          token: ${{ secrets.ERICLYERIC_BOT_TOKEN }}
          release-type: node
